### ISSUE TITLE
The installation encountered a dependency problem

### ISSUE THREAD

**Issue by WuZihao12** [VIS4ROB-lab/HyperSLAM#13]
Hi, thank you for your excellent work. What I want to ask is do I need to install [HyperSensors](https://github.com/VIS4ROB-lab/HyperSensors)、 [HyperState](https://github.com/VIS4ROB-lab/HyperState)
 and [HyperVariables](https://github.com/VIS4ROB-lab/HyperVariables) installing [HyperSLAM](https://github.com/VIS4ROB-lab/HyperSLAM/tree/main) ?

**Comment by McEmzi** [comment]
Yes, _Hyper_SLAM depends on all of these sub-repositories. However, they are automatically fetched when building with CMake (and can be found in the deps folder within your build folder) in the current build system.
