### ISSUE TITLE
When will the whole code Release？

### ISSUE THREAD

**Issue by Gatsby23** [VIS4ROB-lab/HyperSLAM#2]

**Comment by Alex-Beh** [comment]
@Gatsby23 Maybe you can check the develop branch. Although I don't know whether it is the full release version

**Comment by McEmzi** [comment]
@Gatsby23 Thank you for your question. In the meantime, we made the codebase available on the `main` branch as a beta version. As mentioned by @Alex-Beh, the code has already been available for quite some time on the `develop` branch. The `main` branch will also receive additional updates in the coming weeks and months. Once we consider it to be the full release, we will also add the according tag.

**Comment by Gatsby23** [comment]
> @Gatsby23 Thank you for your question. In the meantime, we made the codebase available on the `main` branch as a beta version. As mentioned by @Alex-Beh, the code has already been available for quite some time on the `develop` branch. The `main` branch will also receive additional updates in the coming weeks and months. Once we consider it to be the full release, we will also add the according tag.

OK, Thank you very much
