### ISSUE TITLE
Is this repo validated on Ubuntu 18.04?

### ISSUE THREAD

**Issue by bhyu0924** [VIS4ROB-lab/HyperSLAM#5]
Thanks for your kind contribution.

I just finished building the source code and now I want to run it.
Readme.txt in evaluation folder was checked and virtual env was also made.
But, `pip install -r requirements.txt` is not working.
Even though I changed all dependencies manually to fit on Ubuntu 18.04, PyQT version issue has not been solved.

If this repo is only validated in Ubuntu 20.04 (and ROS noetic), please indicate the proper environments.
(You may want to modify the Preliminaries of Setup & Installation part)

Or if you can branch this repo for ROS melodic, then it would be very nice.

TIA.

**Comment by McEmzi** [comment]
@bhyu0924 The codebase was tested on Ubuntu 20.04. Hence, it is likely that some modifications are necessary to run it on Ubuntu 18.04. However, considering that Ubuntu 22.04 has already been released, it is more likely that we would opt to support  20.04 and 22.04 in favor of 18.04. I will try to emphasize this in the documentation a bit more clearly in a future update.

**Comment by bhyu0924** [comment]
Okay! It was just confusing for me :) 
I am going to check your nice work on Ubuntu 20.04 soon.
Thanks for your effort.
