### ISSUE TITLE
Non-Uniform B-Splines or Uniform B-Splines ?

### ISSUE THREAD

**Issue by SharineLee** [VIS4ROB-lab/HyperSLAM#9]
this code realized Non-Uniform B-Splines or Uniform B-Splines ?

**Comment by McEmzi** [comment]
For the evaluations presented in [Continuous-Time Stereo-Inertial Odometry](https://ieeexplore.ieee.org/document/9772323) we used a uniform B-Spline parametrization with 0.1 seconds spacing between adjacent bases. However, the [HyperState](https://github.com/VIS4ROB-lab/HyperState) repository also contains code to evaluate non-uniform B-Splines (see [temporal interpolators](https://github.com/VIS4ROB-lab/HyperState/blob/main/internal/hyper/state/interpolators/temporal/basis.cpp)) where the non-uniform weights are computed recursively. Hopes this helps.
